export const ADD_CONTACT="ADD_CONTACT";
export const UPDATE_CONTACT="UPDATE_CONTACT";

export const ADD_EDUCATION="ADD_EDUCATION";
export const UPDATE_EDUCATION="UPDATE_EDUCATION";

export const ADD_DOCUMENT="ADD_DOCUMENT";
export const UPDATE_DOCUMENT="UPDATE_DOCUMENT";
